### ISSUE TITLE
fix: sandbox jwtks service is not accessible from outside

### ISSUE THREAD

**Issue by 42atomys** [42Atomys/stud42#166]
**Describe the bug**

The Sandbox JWTKS Service is normally defined to be accessible for everyone to allow developers to develop on s42 easier. At this moment, the service run correctly but is not accessible from outside of k8s cluster.

**To Reproduce**
1. Try to sign a payload on `sandbox.s42.dev:51000` in `insecure`
2. With payload:
```json
{
  "payload": "{}"
}
```

**Expected behavior**
The service must be accessible to everyone

**Additional context**

This configuration must be works locally for everyone
```yaml
# jwtks service relatives configurations
jwtks:
  # Endpoint of the public JWKSet can be used to validate
  # a JWT Token
  endpoints:
    # The endpoint used to retrieve the public key for the JWT token.
    # This endpoint is a HTTP(S) endpoint. If you have access to the
    # DEVENV, you can use the public dev endpoint. Else, use the
    # `jwtks-service` configured locally.
    #
    # In production, the JWTKS endpoint is a HTTPS endpoint. Accessible
    # to the public.
    sets: https://sandbox.s42.dev/.well-knows/jwks
    # The endpoint used to retrieve the public key for the JWT token.
    # This endpoint is a gRPC endpoint. In order to use this endpoint,
    # the `jwtks-service` must be running. If you have access to the DEVENV
    # you can use the public dev endpoint and set `insecure` to `true` to
    # bypass the TLS certificate check during development ONLY.
    #
    # In production, the endpoint should be `secure` and use a TLS
    # certificate. The communication with the signing server is cluster
    # specific and cannot be called from outside the cluster.
    sign: sandbox.s42.dev:51000
 ```
